import 'package:flutter/material.dart';

/// Curated Material icon registry. Categories persist icons by their string
/// [name] so the data stays readable inside exported JSON.
///
/// Includes legacy Cupertino names from schema v1 so migrated data still shows
/// a sensible icon.
class AppIcons {
  AppIcons._();

  static const IconData fallback = Icons.label;

  static const Map<String, IconData> byName = {
    // Current palette.
    'restaurant': Icons.restaurant,
    'directions_car': Icons.directions_car,
    'shopping_bag': Icons.shopping_bag,
    'home': Icons.home,
    'sports_esports': Icons.sports_esports,
    'medical_services': Icons.medical_services,
    'payments': Icons.payments,
    'card_giftcard': Icons.card_giftcard,
    'trending_up': Icons.trending_up,
    'add_circle': Icons.add_circle,
    'local_cafe': Icons.local_cafe,
    'local_grocery_store': Icons.local_grocery_store,
    'flight': Icons.flight,
    'hotel': Icons.hotel,
    'phone_iphone': Icons.phone_iphone,
    'wifi': Icons.wifi,
    'tv': Icons.tv,
    'headphones': Icons.headphones,
    'menu_book': Icons.menu_book,
    'movie': Icons.movie,
    'music_note': Icons.music_note,
    'fitness_center': Icons.fitness_center,
    'pets': Icons.pets,
    'child_care': Icons.child_care,
    'school': Icons.school,
    'work': Icons.work,
    'build': Icons.build,
    'brush': Icons.brush,
    'local_gas_station': Icons.local_gas_station,
    'local_parking': Icons.local_parking,
    'directions_bus': Icons.directions_bus,
    'train': Icons.train,
    'local_hospital': Icons.local_hospital,
    'spa': Icons.spa,
    'checkroom': Icons.checkroom,
    'redeem': Icons.redeem,
    'savings': Icons.savings,
    'account_balance': Icons.account_balance,
    'credit_card': Icons.credit_card,
    'receipt_long': Icons.receipt_long,
    'subscriptions': Icons.subscriptions,
    'sports_soccer': Icons.sports_soccer,
    'beach_access': Icons.beach_access,
    'celebration': Icons.celebration,
    'cake': Icons.cake,
    'local_florist': Icons.local_florist,
    'water_drop': Icons.water_drop,
    'bolt': Icons.bolt,
    'shield': Icons.shield,
    'star': Icons.star,
    'favorite': Icons.favorite,
    'label': Icons.label,
    'attach_money': Icons.attach_money,
    'tag': Icons.tag,
    'more_horiz': Icons.more_horiz,
    // Legacy Cupertino names from schema v1.
    'cart': Icons.shopping_cart,
    'cart_fill': Icons.shopping_cart,
    'bag': Icons.shopping_bag,
    'bag_fill': Icons.shopping_bag,
    'car': Icons.directions_car,
    'bus': Icons.directions_bus,
    'house': Icons.home,
    'house_alt': Icons.home,
    'gamecontroller': Icons.sports_esports,
    'gamecontroller_fill': Icons.sports_esports,
    'bandage': Icons.medical_services,
    'staroflife': Icons.medical_services,
    'money_dollar': Icons.payments,
    'money_yen': Icons.attach_money,
    'money_euro': Icons.attach_money,
    'creditcard': Icons.credit_card,
    'creditcard_fill': Icons.credit_card,
    'chart_bar': Icons.bar_chart,
    'chart_bar_alt_fill': Icons.trending_up,
    'chart_pie': Icons.pie_chart,
    'chart_pie_fill': Icons.pie_chart,
    'gift': Icons.card_giftcard,
    'gift_fill': Icons.card_giftcard,
    'plus_circle': Icons.add_circle,
    'plus_app': Icons.add_circle,
    'heart': Icons.favorite,
    'heart_fill': Icons.favorite,
    'book': Icons.menu_book,
    'book_fill': Icons.menu_book,
    'film': Icons.movie,
    'film_fill': Icons.movie,
    'music_note_2': Icons.music_note,
    'briefcase': Icons.work,
    'paw': Icons.pets,
    'paw_solid': Icons.pets,
    'airplane': Icons.flight,
    'phone': Icons.phone_iphone,
    'desktopcomputer': Icons.desktop_windows,
    'eyeglasses': Icons.visibility,
    'paintbrush': Icons.brush,
    'scissors': Icons.content_cut,
    'hammer': Icons.build,
    'wrench': Icons.build,
    'lightbulb': Icons.lightbulb,
    'drop': Icons.water_drop,
    'drop_fill': Icons.water_drop,
    'flame': Icons.local_fire_department,
    'snow': Icons.ac_unit,
    'wind': Icons.air,
    'umbrella': Icons.beach_access,
    'sun_max': Icons.wb_sunny,
    'moon': Icons.dark_mode,
    'cloud': Icons.cloud,
    'cloud_fill': Icons.cloud,
    'person': Icons.person,
    'person_2': Icons.person,
    'ticket': Icons.confirmation_number,
    'star_fill': Icons.star,
    'flag': Icons.flag,
    'bookmark': Icons.bookmark,
    'folder': Icons.folder,
    'folder_fill': Icons.folder,
    'doc': Icons.description,
    'doc_text': Icons.description,
    'doc_plaintext': Icons.description,
    'archivebox': Icons.inventory_2,
    'tray': Icons.inbox,
    'bed_double': Icons.bed,
    'table': Icons.table_restaurant,
    'location': Icons.location_on,
    'globe': Icons.public,
    'sparkles': Icons.auto_awesome,
    'wand_stars': Icons.auto_awesome,
    'calendar': Icons.calendar_month,
    'calendar_badge_plus': Icons.event,
    'clock': Icons.schedule,
    'clock_solid': Icons.schedule,
    'bell': Icons.notifications,
    'bell_fill': Icons.notifications,
    'lock': Icons.lock,
    'gear': Icons.settings,
    'gear_alt': Icons.settings,
    'minus': Icons.remove,
    'percent': Icons.percent,
    'number': Icons.numbers,
    'barcode': Icons.qr_code,
    'qrcode': Icons.qr_code,
    'textformat': Icons.text_fields,
    'thermometer': Icons.thermostat,
    'tortoise': Icons.pets,
    'hare': Icons.pets,
    'ant': Icons.pest_control,
  };

  static IconData resolve(String? name) {
    if (name == null || name.isEmpty) return fallback;
    return byName[name] ?? fallback;
  }
}
